name: MLOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-sistemi:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Receive the codes from Github
      uses: actions/checkout@v3

    - name: 2. Set Up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 3. Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: 4. Run API and Model Tests
      run: |
        pytest test_main.py
